# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCP4():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_cP4(self):
    self.driver.get("https://www.demoblaze.com/index.html")
    self.driver.set_window_size(788, 816)
    self.driver.find_element(By.ID, "itemc").click()
    self.driver.find_element(By.LINK_TEXT, "Laptops").click()
    self.driver.find_element(By.LINK_TEXT, "Monitors").click()
    self.driver.execute_script("window.scrollTo(0,332)")
    self.driver.find_element(By.LINK_TEXT, "Samsung galaxy s6").click()
    self.driver.find_element(By.LINK_TEXT, "Nokia lumia 1520").click()
    self.driver.execute_script("window.scrollTo(0,332)")
    self.driver.execute_script("window.scrollTo(0,664)")
    self.driver.execute_script("window.scrollTo(0,1286.4000244140625)")
    self.driver.find_element(By.ID, "itemc").click()
    self.driver.execute_script("window.scrollTo(0,611.2000122070312)")
    self.driver.find_element(By.ID, "itemc").click()
    self.driver.find_element(By.LINK_TEXT, "Laptops").click()
    self.driver.find_element(By.LINK_TEXT, "Sony vaio i5").click()
    self.driver.find_element(By.LINK_TEXT, "Monitors").click()
    self.driver.find_element(By.LINK_TEXT, "Apple monitor 24").click()
    self.driver.find_element(By.LINK_TEXT, "Samsung galaxy s6").click()
  
