# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUntitled():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_untitled(self):
    self.driver.get("https://www.demoblaze.com/index.html")
    self.driver.set_window_size(1552, 832)
    assert self.driver.title == "STORE"
    self.driver.find_element(By.ID, "login2").click()
    time.sleep(10)
    assert self.driver.find_elements(By.ID, "loginusername") is True
    self.driver.find_element(By.ID, "loginusername").click()
    time.sleep(10)
    self.driver.find_element(By.ID, "loginusername").send_keys("a")
    self.driver.find_element(By.ID, "loginpassword").click()
    self.driver.find_element(By.ID, "loginpassword").send_keys("a")
    self.driver.find_element(By.CSS_SELECTOR, "#logInModal .btn-primary").click()
    time.sleep(10)
    self.driver.find_element(By.ID, "nameofuser").click()
  
